### ISSUE TITLE
Introduce intermediate doc representation, move processing out of render cycle

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/react-asciidoc#17]
Right now, when we use this library, AsciiDoc processing happens at render time, which means the 2MB `asciidoctor.js` ends up in the client bundle because rendering happens on both client and server.

<img width="1384" alt="image" src="https://github.com/oxidecomputer/react-asciidoc/assets/3612203/869aac3f-822e-4231-abea-9f858021dd61">

https://docs-git-vercel-vite-oxidecomputer.vercel.app/guides/introduction 

In practice. this is not so bad:

1. it gzips to 660k (not great but not 2MB), 
2. it caches locally, and 
3. the SSRed HTML response is cached in CDN
 
So the site still loads in a few hundred ms. It doesn't feel slow except sometimes on the first time a given page has been loaded (a cache miss). Still, it would be nice to avoid all that, and conceptually, it gives me a little anxiety that simple components depend on a complex "live" objects from asciidoctor.js, when in practice we only need a few bits of data off them.

<details>
<summary>Examples of dependency on the full <code>asciidoctor.js</code> object</summary>

https://github.com/oxidecomputer/react-asciidoc/blob/ce1224a58fb79824e9e58c255201eb52811b3520/src/asciidoc/templates/Outline.tsx#L5-L26

https://github.com/oxidecomputer/design-system/blob/b67ce812222912b14bf2d408715161232449631a/components/src/AsciiDoc/Admonition.tsx#L13-L15

</details>

It we took the data we need and stuck it in a "dead" serializable JSON object, we could choose to either do all the processing at build time, or if we didn't feel like getting complicated, we could at least do it in a Remix loader and send it down to the client already processed, which means it is cached in CDN and the client doesn't need to know about asciidoctor at all, and a given component's data dependencies are much easier to understand by looking at the props.

**Comment by benjaminleonard** [comment]
Done with the `prepareDocument` PR
