### ISSUE TITLE
slight misrendering on block quotes

### ISSUE THREAD

**Issue by bcantrill** [oxidecomputer/react-asciidoc#25]
Block quotes seem to be slightly misrendered, e.g., this quote from [RFD 485](https://rfd.shared.oxide.computer/rfd/0485):

![2024-06-05-10-39-14_755x277](https://github.com/oxidecomputer/rfd-site/assets/328614/9b406483-7d41-4d99-bf6e-450ba0244fbf)

(Note the lack of a space or comma between the author and the work.)

Here is the asciidoc source for that quote:

```
==== Responsibility

"Uneasy is the head that wears a crown."
-- William Shakespeare, Henry IV, Part 2

```

**Comment by david-crespo** [comment]
I think this is the relevant code:

https://github.com/oxidecomputer/react-asciidoc/blob/fc45a5210954ae73f53210b5aef84bb62818a6f8/src/asciidoc/templates/Quote.tsx#L20-L26

It's possible you can work around it for now by putting the attribution in quotes.

**Comment by benjaminleonard** [comment]
Merged fix into the design system though we won't see this fixed on the rfd site until the ongoing react-asciidoc upgrade is done.
